version: "3.8"

services:
    web:
        container_name: webserver
        build:
            context: .
            dockerfile: docker/apache/Dockerfile
            # dockerfile: docker/nginx/Dockerfile
        volumes:
            - ./public:/var/www/html/public
        ports:
            - ${WEB_PORT:-80}:80
        depends_on:
            - php
            - mysql
        networks:
            - devnet
        env_file:
            - ./.env
            - ./docker/docker.env
    php:
        container_name: php
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        ports:
            - ${PHP_PORT:-9000}:9000
        volumes:
            - .:/var/www/html
        networks:
            - devnet
        env_file:
            - ./.env
            - ./docker/docker.env
    mysql:
        container_name: mysql
        image: mariadb:10.6
        # image: mysql:5.7
        volumes:
            - db_data:/var/lib/mysql
        ports:
            - ${MYSQL_PORT:-3306}:3306
        networks:
            - devnet
        env_file:
            - ./.env
            - ./docker/docker.env
    composer:
        container_name: composer
        build:
            context: .
            dockerfile: docker/composer/Dockerfile
        volumes:
            - .:/var/www/html
        working_dir: /var/www/html
        networks:
            - devnet
        env_file:
            - ./.env
            - ./docker/docker.env
    npm:
        container_name: npm
        image: node:lts-alpine
        ports:
            - ${NODE_PORT:-3000}:3000
        working_dir: /var/www/html
        volumes:
            - .:/var/www/html
        # entrypoint: [ 'npm' ]
        networks:
            - devnet
        env_file:
            - ./.env
            - ./docker/docker.env
    mailhog:
        image: mailhog/mailhog:latest
        container_name: mailhog
        ports:
            - ${MAIL_PORT:-1025}:1025
            - ${MAIL_PORT_2:-8025}:8025
        networks:
            - devnet
        env_file:
            - ./.env
            - ./docker/docker.env
networks:
    devnet:
        driver: 'bridge'
volumes:
    db_data:
        driver: 'local'
