version: '3'

services:
    app:
        build:
            # matches this: docker build -t slim-php -f docker/php/Dockerfile .
            context: .
            dockerfile: docker/php/Dockerfile
        volumes:
            - .:/srv/app
    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        ports:
            - 9000:80
        volumes:
            - ./public:/srv/app/public # nginx cares only for public folder
